# Generated by Django 4.0.1 on 2022-01-13 09:03

from django.db import migrations, models

from board.models import Board, Article

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('name', models.CharField(max_length=100, verbose_name='상품명(내부용)')),
            ],
        ),
    ]
