# Generated by Django 4.0.1 on 2022-01-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from board.models import Article, Board


def gen_data(app, schema_editor):
    board = Board(name="공지사항")
    board.save()
    for id in range(1, 20):
        subject = f"안녕하세요{id}"
        content = f"좋은 아침입니다.{id}"
        Article(board_id=board.id, user_id=1, subject=subject, content=content).save()
    for id in range(1, 20):
        subject = f"다들 점심은 드셨나요?{id}"
        content = f"맛있게 먹었습니다..{id}"
        Article(board_id=board.id, user_id=1, subject=subject, content=content).save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_blind', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(gen_data),
    ]
